/**
 * Flowtype definitions for buttons
 * Generated by Flowgen from a Typescript Definition
 * Flowgen v1.2.0
 * Author: [Joar Wilk](http://twitter.com/joarwilk)
 * Repo: http://github.com/joarwilk/flowgen
 */

declare export function getMoviesButton(theatreCode: string, title?: string): IButtondeclare export function getShowtimeButton(m: IMovieDetail, date: Date): IButtondeclare export function getMovieDescriptionButton(m: IMovieDetail): IButtondeclare export function getWatchYoutubeTrailerButton(url: string): IButtondeclare export function getWatchEmbedTrailerButton(url: string, title: string): IButtondeclare export function getMovieButtons(m: IMovieDetail, date: Date): IButton[] declare export function getPurchaseButton(s: IPerformance, theatreCode?: string): IButtondeclare export function setTheatreLocationButton(loc: ITheatreLocation): IButtondeclare export function getSettingsButton(): IButtondeclare export function viewRegalMoviesButton(): IButton