/**
 * Flowtype definitions for config
 * Generated by Flowgen from a Typescript Definition
 * Flowgen v1.2.0
 * Author: [Joar Wilk](http://twitter.com/joarwilk)
 * Repo: http://github.com/joarwilk/flowgen
 */

declare export var AWS_REGION: ;
declare export var AWS_REGALBOT_API_GATEWAY_BASE: any;
declare export var LUIS_API_ROOT: any;
declare export var FB_VERIFY_TOKEN: any;
declare export var FB_GRAPH_API_ROOT: ;
declare export var FB_PAGE_ACCESS_TOKEN: any;
declare export var REGAL_API_ROOT: ;
declare export var REGAL_AUTH_USER: any;
declare export var REGAL_OCP_APIM_SUBSCRIPTION_KEY: any;
declare export var REGAL_ONELINK_DEEPLINK_BASE: any;
declare export var REGAL_ONELINK_PID: any;
declare export function getTicketPurchaseDeepLinkUrl(date: Date, theatreCode: string, webUrl: string, performanceId: number): any