/**
 * Flowtype definitions for i18n
 * Generated by Flowgen from a Typescript Definition
 * Flowgen v1.2.0
 * Author: [Joar Wilk](http://twitter.com/joarwilk)
 * Repo: http://github.com/joarwilk/flowgen
 */

declare export var locales: string[];
declare export var messages: {
    en - us: {
        ERROR_UNCERTAIN_SCORE: string,
        ERROR_INTENT_NONE: string,
        ERROR_UNKNOWN_INTENT: string
    }
};