/**
 * Flowtype definitions for i18n
 * Generated by Flowgen from a Typescript Definition
 * Flowgen v1.2.0
 * Author: [Joar Wilk](http://twitter.com/joarwilk)
 * Repo: http://github.com/joarwilk/flowgen
 */

declare export var getLocale: () => string;
declare export var getString: (key: any) => string;
declare export var getPhrase: any;