/**
 * Flowtype definitions for interfaces
 * Generated by Flowgen from a Typescript Definition
 * Flowgen v1.2.0
 * Author: [Joar Wilk](http://twitter.com/joarwilk)
 * Repo: http://github.com/joarwilk/flowgen
 */

declare export type LuisIntentEnum = ExpressThanks |
    Parting |
    SeekShowtime |
    Revise |
    Assent |
    AskRCC |
    Banter |
    ExpressDelight |
    SeekMovieInfo |
    DiscussConcessions |
    Decline |
    AskAdvice |
    Greet |
    None |
    ExpressFrustration |
    SeekShowtime;
declare export interface ILuisIntent {
    intent: LuisIntentEnum,
        score: number
}
declare export interface ILuisEntity {
    entity: string,
        type: string,
        startIndex: number,
        endIndex: number,
        score: number,
        resolution: any
}
declare export interface ILuisData {
    query: string | void,
        intents: ILuisIntent[],
        entities: ILuisEntity[]
}