/**
 * Flowtype definitions for movies
 * Generated by Flowgen from a Typescript Definition
 * Flowgen v1.2.0
 * Author: [Joar Wilk](http://twitter.com/joarwilk)
 * Repo: http://github.com/joarwilk/flowgen
 */

declare export function sendMoviePayload(
    senderId: string,
    movies: IMovieDetail[],
    theatreCode: string,
    date: Date): Promise<{}>declare export function sendSingleMoviePayload(
    senderId: string,
    movie: IShowtimes,
    theatreCode: string,
    date: Date): Promise<{} >