/**
 * Flowtype definitions for persistentMenu
 * Generated by Flowgen from a Typescript Definition
 * Flowgen v1.2.0
 * Author: [Joar Wilk](http://twitter.com/joarwilk)
 * Repo: http://github.com/joarwilk/flowgen
 */

declare export function showAuthenticatedMenu(senderId: string): Promise<{}>declare export function showUnauthenticatedMenu(senderId: string): Promise<{} >