/**
 * Flowtype definitions for quickReply
 * Generated by Flowgen from a Typescript Definition
 * Flowgen v1.2.0
 * Author: [Joar Wilk](http://twitter.com/joarwilk)
 * Repo: http://github.com/joarwilk/flowgen
 */

declare export function showLocationQuickReplyButton(userId: string, locationPrompt?: string): Promise<{}>declare export function showQuickReplyForErrorHandling(userId: string, errorHandlingPrompt: string): Promise<{}>declare export function showQuickRepliesForDisambiguatingMovieTitles(userId: string, titleList: string[]): Promise<{} >