/**
 * Flowtype definitions for responseContent.fl
 * Generated by Flowgen from a Typescript Definition
 * Flowgen v1.2.0
 * Author: [Joar Wilk](http://twitter.com/joarwilk)
 * Repo: http://github.com/joarwilk/flowgen
 */

declare export var listOfGreetings: string[];
declare export var listOfFarewells: string[];
declare export var listOfCannotFindMovieInfoResponses: string[];
declare export var listOfDoNotUnderstandQueryResponses: string[];
declare export var listOfUserHitYesResponses: string[];
declare export var listOfUserHitNoResponses: string[];
declare export var listOfDoNotUnderstandRequestedPayloadResponses: string[];
declare export var listOfCannotFindShowtimesResponses: string[];
declare export var getStartedShareLocationPrompt: string;
declare export var shareLocationDuringConversationPrompt: string;
declare export function randomResponse(responseList: string[]): string