/**
 * Flowtype definitions for settings.fl
 * Generated by Flowgen from a Typescript Definition
 * Flowgen v1.2.0
 * Author: [Joar Wilk](http://twitter.com/joarwilk)
 * Repo: http://github.com/joarwilk/flowgen
 */

declare export default function handleSettingsIntent(message: IMessagingReceived, luisData: ILuisData): Promise<{} >