/**
 * Flowtype definitions for user
 * Generated by Flowgen from a Typescript Definition
 * Flowgen v1.2.0
 * Author: [Joar Wilk](http://twitter.com/joarwilk)
 * Repo: http://github.com/joarwilk/flowgen
 */

declare export interface IUser {
    id: string,
        zip?: number
}
declare export function getMockUserWithLocation(): IUserdeclare export function getMockUserWithoutLocation(): IUser