export declare const AWS_REGION = "us-east-1";
export declare const AWS_REGALBOT_API_GATEWAY_BASE: any;
export declare const LUIS_API_ROOT: any;
export declare const FB_VERIFY_TOKEN: any;
export declare const FB_GRAPH_API_ROOT = "https://graph.facebook.com/v2.6";
export declare const FB_PAGE_ACCESS_TOKEN: any;
export declare const REGAL_API_ROOT = "https://api.regmovies.com/v1";
export declare const REGAL_AUTH_USER: any;
export declare const REGAL_OCP_APIM_SUBSCRIPTION_KEY: any;
export declare const REGAL_ONELINK_DEEPLINK_BASE: any;
export declare const REGAL_ONELINK_PID: any;
export declare function getTicketPurchaseDeepLinkUrl(date: Date, theatreCode: string, webUrl: string, performanceId: number): any;
